### ISSUE TITLE
APN storage space is too small

### ISSUE THREAD

**Issue by TonyArmitstead** [geolink/opentracker#12]
In the UK, using Tesco mobile phone service the APN name is 'prepay.tesco-mobile.com' which is longer than the 20 chars allowed for. I had to increase this to get a functional network connection.
Note also, that no error is generated when sending an SMS to set the APN when the sent APN is too long.

**Comment by Neville77** [comment]
I am having a similar issue in Australia- Optus APN - internet works fine bit I can not get Telstra APN of telstra.internet to work.
 Solved this by changing the code. SMS command does not save even tho I get a SMS reply confirming change.

**Comment by m4rkw** [comment]
Submitted a pull request to increase the apn buffer to 64 bytes, should be sufficient for all networks.
