### ISSUE TITLE
FYI: Wiki Started

### ISSUE THREAD

**Issue by ilevans** [geolink/opentracker#19]
Hi All.

I started an initial Wiki page (it had to start sometime).

I would like to see it updated when a known workable and tested version of the code is available so that new people are able to locate it when they begin.

Some suggestions.
- Record the date and a link (a tag would be preferable) to the commit version. (ensure new people do not begin with buggy code)
- a Wiki page of enhancements that different people are working on for the code. (I hate re-inventing the wheel)

regards
Ian
@ilevans

**Comment by opensourcegps** [comment]
thank you for starting the Wiki, I've added the link to Readme.

In regards on workable version, we are preparing stable release and will generate release through github. So there will be stable version always available.
