### ISSUE TITLE
Error while sending update to web

### ISSUE THREAD

**Issue by AnandSingh** [geolink/opentracker#2]
Why its showing below error message ....

Modem Reply:
AT+QIRD=0,1,0,100

+QIRD: 78.46.45.61:80,TCP,100
.php

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><

**Comment by opensourcegps** [comment]
are you using unchanged software from this repository?
Make sure that HOSTNAME is set to updates.geolink.io

**Comment by AnandSingh** [comment]
Thanks Got it resolved.

**Comment by m4rkw** [comment]
Closing as this seems to be resolved
