### ISSUE TITLE
WEBSERVER Date/Time entry not consistent with Displayed Track Date/Time

### ISSUE THREAD

**Issue by ilevans** [geolink/opentracker#29]
On the website tracks display their date/time in the Local Browser Time Zone correctly.

It is however necessary to enter a date/time range as GMT+1 or GMT+2 time zone to find them.

EG: trip (GMT+10) 29-Jul-2015 16:58 - 17:17
 is found by entering  29-Jul-2015 07:58 - 08:16 (GMT+1)

and trip (GMT+10) 30-Jul-2015 05:01 - 05:02
is found by entering 29-Jul-2015 21:01 - 21:02 (GMT+2)

Could the date/time entry be modified so that the date/time can be entered in the Local Browser timezone as well please.

**Comment by opensourcegps** [comment]
New option Timezone was added into General -> Profile. Please set your timezone and try to search tracks normally.

**Comment by ilevans** [comment]
Excellent. 

It work perfectly.

many thanks Andrey
