### ISSUE TITLE
Programming on Linux and Mac

### ISSUE THREAD

**Issue by varlux** [geolink/opentracker#35]
I'm trying to install OpenTracker board in Arduino IDE (Linux 32bit) but, when i press "install" button i read a red message "Tool bossac is not available for your operating system" and procedure stops. Can somebody help me? Thanks

**Comment by fhasex20** [comment]
You have to build bossac from source.
Git clone https://github.com/geolink/opentracker-bossa.git
Git clone ‎ https://github.com/geolink/opentracker-arduino-board.git
Edit ‎local package_opentracker_index.json
And remove bossac entry. Dirty, but should work

Ferdinand Haselbacher

**Comment by salanki** [comment]
The same works for Mac. I however had to modify the opentracker-bossa Makefile:

```
COMMON_CXXFLAGS=-arch i386 -arch x86_64 -mmacosx-version-min=10.10 -stdlib=libc++ -std=c++11
COMMON_LDFLAGS=-arch i386 -arch x86_64 -mmacosx-version-min=10.10
```

and also install wxmac:

```
brew install wxmac
```

You might also need to patch

```
/Users/sorcer/Library/Arduino15/packages/opentracker/hardware/sam/1.0.1/platform.txt
```

Change row 86 to:

```
tools.bossac.path=/usr/bin/
```

**Comment by ppescher** [comment]
FYI, the board suport package now includes linux binaries (since v1.0.1)
See https://github.com/geolink/opentracker-arduino-board/commit/98105ba1d54bdc6c8949accd23c333a4d9dc58de

To build the command line tool, you don't actually need wxWidgets. Just "make bin/bossac"

**Comment by ppescher** [comment]
Can anybody please test the Mac OSX binaries, before the official release?

You should be able to get v1.0.2 of the board support package using this URL in your preferences: https://github.com/geolink/opentracker-arduino-board/raw/1.0.2/package_opentracker_index.json

That includes the OSX binary of the BOSSA tool.

**Comment by varlux** [comment]
Grazie Paolo, seguiro' il tuo consiglio e ti faro' sapere

**Comment by varlux** [comment]
OK, it works on Linux, Thanks!

**Comment by ppescher** [comment]
Thank you varlux.
Any Mac user that can test on that platform?
