### ISSUE TITLE
Reset GPS

### ISSUE THREAD

**Issue by varlux** [geolink/opentracker#36]
I tried to reset GPS with this code

DigitalWrite(resetpin, HIGH);
delay(50);
DigitalWrite(resetpin, LOW);

but GPS do not reset AND i lose data from Serial1.......

Can you help me?

**Comment by ppescher** [comment]
```
pinMode(PIN_RESET_GPS, OUTPUT);
digitalWrite(PIN_RESET_GPS, HIGH);
delay(50);
digitalWrite(PIN_RESET_GPS, LOW);
```

Have you tried this sequence?
When the module is reset, data flow on the serial port is stopped and resumed after reset is complete.

**Comment by varlux** [comment]
OK.... it works.

Thanks
