### ISSUE TITLE
Storage commented out?

### ISSUE THREAD

**Issue by salanki** [geolink/opentracker#38]
It seems as all calls to the storage code is actually commented out. What is the reason behind that, will it not work?

**Comment by opensourcegps** [comment]
It will not work, the code in storage.ino is slightly broken, however very close to working. The tricky part is not to write to the same memory addresses.

**Comment by salanki** [comment]
Ok. Thank you. Did you give up on making it work or just didn't have a need for it?

**Comment by opensourcegps** [comment]
Nobody was actively asking for it. But I think it's a great feature and should be added in future.
