### ISSUE TITLE
Setting up web server for Ruby Scripts

### ISSUE THREAD

**Issue by alskyline** [geolink/opentracker#43]
I'm really sorry if this is not the place for this. Can you please help me with how to setup the web server  for my own logging server? I had things setup for the php code but now that it is in ruby I'm lost. Maybe something for the wiki? Do you have to use this code in a ruby on rails application?

**Comment by m4rkw** [comment]
Hi there,

It doesn't need rails, it just runs as a standalone daemon.  First copy daemon_config.rb.example to daemon_config.rb and set the config how you want it, then run the daemon with:

./daemon.rb

You'll need to set the tracker.h config to RAW mode and set the IP address and port to the IP/port configured in the daemon.

Alternatively you may find it easier to use the http post method as that way you can fire the data at a php script.

Shout if you need more help.

Mark

**Comment by alskyline** [comment]
Thank You
