### ISSUE TITLE
Pin mapping not clear

### ISSUE THREAD

**Issue by dgiardini** [geolink/opentracker#48]
Not sure how to match I/O numbering with labels on circuits or schematics. Seems there is not macros defined for EXT_TX, EXT_RX,IO_TO_EXT and so.

**Comment by ppescher** [comment]
Please see: https://github.com/geolink/opentracker-arduino-board/blob/master/1.0.2/variants/geolink_opentracker/variant.h

There you can find PIN_EXT_RX and PIN_EXT_RX.

IO_TO_EXT is a signal that goes from the MAIN connector to the Expansion interface directly. It is not connected to the MCU, so there is no pin mapping defined. It is reserved for use by expansion cards.
