### ISSUE TITLE
Logs in storage 

### ISSUE THREAD

**Issue by dgiardini** [geolink/opentracker#49]
Would be nice to get this feature working properly. It would be a problem to write records from the beginning instead a circular buffer ? This seem to be easier.  Is the ring buffer approach intended to extend the life of the eeprom not writing always the same places ?

**Comment by ppescher** [comment]
There was some development going on lately, including logs storage functionality. You may want to give it a try.
The approach is to use the all the available memory of the configured block, before going back overwriting old logs. So you are right, this is a circular buffer. And one of the reasons is to extend the flash memory life, but also to keep old data if possible, until you can send it to the server.
