### ISSUE TITLE
arduino 1.6.8 and avr/dtostrf.h

### ISSUE THREAD

**Issue by oscaroxy** [geolink/opentracker#51]
I've setted Arduino Uno but when I compile receive the error:

```
/Users/oscar/Desktop/opentracker-master/Opentracker_3_0_1/Opentracker_3_0_1.ino:7:25: fatal error: avr/dtostrf.h: No such file or directory
 #include <avr/dtostrf.h>

```

I'm newbiein arduino, so How do I resolve it?
thanks

**Comment by oscaroxy** [comment]
I resolve, I installed "OpenTracker Boards" and all i's ok.
thanks

**Comment by fhasex20** [comment]
Some things in live, just resolve
Am 08.05.2016 10:29 schrieb "oscaroxy" <notifications@github.com>:
