### ISSUE TITLE
Arduino IDE integration files for 1.0.3

### ISSUE THREAD

**Issue by Daniel-dk** [geolink/opentracker#56]
Using Arduino IDE 1.6.9 
Windows 10

Following the IDE integration instructions from https://github.com/geolink/opentracker-arduino-board which points to the master branch only lists up to 1.0.2

![master branch](https://cloud.githubusercontent.com/assets/582384/16483479/e313e85e-3eb4-11e6-815f-3fb89068f710.PNG)

when installing 1.0.3 by directly [referencing its json file](https://raw.githubusercontent.com/geolink/opentracker-arduino-board/1.0.3/package_opentracker_index.json) there seems to be some information missing and compilation fails.

![Opentracker 1.0.3 boards manager ](https://cloud.githubusercontent.com/assets/582384/16482567/a3030c62-3eb0-11e6-822d-2c10b38ee015.PNG)
![Opentracker 1.0.3 menu](https://cloud.githubusercontent.com/assets/582384/16482588/c101dcac-3eb0-11e6-9090-2fa3ca13b38a.PNG)
![Opentracker 1.0.3 Compilation error](https://cloud.githubusercontent.com/assets/582384/16482614/d21625e8-3eb0-11e6-894a-0e03e3f7cbfb.PNG)

**Comment by ppescher** [comment]
Make sure you uninstalled the old version.
Check if you have some left-over from the previous version in your folder: %LocalAppData%\Arduino15\packages\opentracker (on Windows)
In particular, under "opentracker\hardware\sam" there should be only one folder named "1.0.3"

FYI: The new version will be soon merged into the master branch. That should facilitate upgrading (but I've seen some IDE versions still failing to clean up properly).

**Comment by Daniel-dk** [comment]
That was the issue, 
There were some directories left over in 1.0.2 with "NUL" files in them - probably form an incomplete removal.

after removing 1.0.2 from the arduino packages the IDE successfully uses 1.0.3
