### ISSUE TITLE
How do I know which Hardware version I have?

### ISSUE THREAD

**Issue by VernonBreet** [geolink/opentracker#58]

**Comment by ppescher** [comment]
The hardware revision is printed on the board silkscreen, in the bottom right corner, near the GPS antenna.

Sample of revision 2.3
![hwrev2 3](https://cloud.githubusercontent.com/assets/8069470/16867820/5d62653e-4a74-11e6-892b-c565ba926d87.jpg)

Sample of revision 2.4
![hwrev2 4](https://cloud.githubusercontent.com/assets/8069470/16867861/9c29dea0-4a74-11e6-9093-092725a067b0.jpg)

**Comment by VernonBreet** [comment]
Thank you.
