### ISSUE TITLE
Is it possible to change the setup of the QuectelL76?

### ISSUE THREAD

**Issue by ramunter** [geolink/opentracker#59]
The gps module supports a 10hz update rate and 115200 BAUD rate but the default settings are 1 hz and 9600 BAUD. Is there anyway to change these through the OpenTracker board?

**Comment by ppescher** [comment]
Yes. You can modify the firmware using Arduino IDE.
The modified firmware should configure the GPS according to your needs.
You can get the L76 serial protocol from Quectel: http://www.quectel.com/UploadImage/Downlad/Quectel_L76_Series_Protocol_Specification_V2.0.pdf
Look for packet PMTK_SET_NMEA_BAUDRATE and PMTK_SET_POS_FIX (updated docs say minimum interval is 100ms => 10Hz)
