### ISSUE TITLE
Builtin antennas

### ISSUE THREAD

**Issue by cristianormoraes** [geolink/opentracker#61]
Why not builtin GSM and GPS antennas?

regards,

Cristiano

**Comment by Daniel-dk** [comment]
in some cases its easier to mount the device in the lower body of a vehicle and run antennae to a place where they can see the sky, there are units ( not OpenTracker ) that use internal antennae and are mounted in other areas of the vehicle so one cannot trace an antenna cable back to the unit.

trackers for "Telemetry" are different to trackers made for "Recovery"
