### ISSUE TITLE
Open Tracker - failed auto-baudrate error

### ISSUE THREAD

**Issue by haroon-rehman** [geolink/opentracker#68]
Hi,
After couple of days of working my open tracker gives me only one message on serial port "ailed auto-baudrate error" and after 4 or 5 retry attempts it stops gsm connection. What can cause this and how to fix it. I have attached image of what i see on serial monitor.

Thanks for any help offered.

Regards,
Haroon
![image](https://cloud.githubusercontent.com/assets/25265150/24861931/913cffde-1e0b-11e7-8c98-cdedaeddf52b.png)

**Comment by haroon-rehman** [comment]
![image](https://cloud.githubusercontent.com/assets/25265150/24863666/dc141810-1e12-11e7-8f6f-9fb541d16e5e.png)

**Comment by ppescher** [comment]
Try to add the following code after https://github.com/geolink/opentracker/blob/master/OpenTracker/gsm.ino#L62
`debug_print("read status");`

Just before the line that starts with "return".

Your code should look like:
```
#if MODEM_UG96
  // inverted status signal
  debug_print("read status");
  return digitalRead(PIN_STATUS_GSM) != HIGH;
#else
```

Load the modified sketch and check if you can see the message "read status" in the serial log.

**Comment by haroon-rehman** [comment]
Hi Paolo,


Yes I can see the 'read status' message in the logs.


[cid:eebaf623-b8b4-49b1-87e8-c9e80ea20caf]


Regards,

Haroon

Orion Systems

________________________________

**Comment by haroon-rehman** [comment]
![image](https://cloud.githubusercontent.com/assets/25265150/24893979/1d8d2356-1e98-11e7-9f97-e5277b6c20d5.png)

**Comment by ppescher** [comment]
Stupid question, but I must ask: are you sure you have the 3G modem on your board?
You should see "Quectel UG96" written on the top white label.

If this is actually an UG96 (3G) then the modem is not starting up (STATUS pin never goes high). Which is confirmed by the green LED always off.

There might be several causes to that. First, please check your power input: if the input voltage is too low or the current provided by your power source is not enough, the modem will not start.

If you have a Voltmeter and some spare male headers or solid wires, you can probe the following voltages on the expansion connector:

![voltage_check](https://cloud.githubusercontent.com/assets/8069470/24900594/a814d710-1ea4-11e7-9180-edfb328b716f.jpg)

Please report your readings, along with your power source voltage/current rating.

**Comment by haroon-rehman** [comment]
Hi Paolo,
It is a UG96 chip.
The power adapter used is 12VDC, 1500 mA. The tracker worked on it for almost 2 days before i started getting this problem
The voltages on the expansion connector are same as indicated in your pics. I have attached some images below;
![image](https://cloud.githubusercontent.com/assets/25265150/24901549/80644516-1eb8-11e7-9c38-63f484da2b11.png)

![image](https://cloud.githubusercontent.com/assets/25265150/24901567/9315b1ea-1eb8-11e7-8b6d-980750fbda98.png)

![image](https://cloud.githubusercontent.com/assets/25265150/24901583/9c78399c-1eb8-11e7-8346-e773670b5762.png)

![image](https://cloud.githubusercontent.com/assets/25265150/24901596/a440d238-1eb8-11e7-86c4-cbafaf5b143e.png)

**Comment by ppescher** [comment]
Voltages are correct, also power supply rating is fine.

Could you try to power on the device without the SIM card?
And check the serial log and the green LED.

**Comment by haroon-rehman** [comment]
Hi mate,
Its still the same. No green light. See the image below.

![image](https://cloud.githubusercontent.com/assets/25265150/24905065/a8b05a18-1ec3-11e7-9bca-35416426b557.png)

**Comment by Codematic** [comment]
Any final solution for this? I have the same issue which appeared after first flash try.

**Comment by ppescher** [comment]
Here the modem did not reply at all, your case is different. See https://github.com/geolink/opentracker/issues/72
