### ISSUE TITLE
no updates are sent

### ISSUE THREAD

**Issue by Chrescht** [geolink/opentracker#76]
Hi there,

my issue is I can't see any updates on the live map.
I did set the APN by sms command, also finally got to see the tracker's debug messages, and one of them is talking about a wrong key. What key would that be?

Also:
- how do I remove a "unit" on mydomain.geolink.io?
- what is the "remote key"? You don't talk about it in your startup guide (https://geolink.io/guide.php)
- how do I check the currently installed opentracker software version?
- how would I go about updating it?

I'd be really happy to get this sorted out.

ps: I have no debug file available now, but I can send it later.

**Comment by opensourcegps** [comment]
Hi Chrescht, 

please check your unit key under Units -> [Your unit] -> Options -> Remote Key. 

It must match the key set in firmware (tracker.h):

```
#define KEY "cSQ88qShwC3" 
```
You can delete units under Settings -> Branding -> Allowed IMEI
You can update firmware via Adruino IDE. 

I hope this helps.

**Comment by Chrescht** [comment]
Thanks for your fast answer.
I got the opentracker because it's supposed to work more or less out of the box with geolink.
- how come there is no mention at all about that key?
- is there no way to set that key with an sms command?
- latest version seems to be 3.2.0, but nowhere can I see how to update the firmware. It's probably only a couple of manipulations using the IDE but come on guys, just include a quick manual for the less experienced

**Comment by opensourcegps** [comment]
It normally works out of the box. The key is saved on the first connect from the tracker. So it's not required to deal with it. It is there to add additional security to your data and to make sure data is received from your device. 

It is strange that you got key saved differently, could be that you made some manual requests for your IMEI number or key mismatch just happened by itself?

In case you are using default firmware, simply set key in the web interface:

```
Units -> [Your unit] -> Options -> Remote Key.
```
to 

```
cSQ88qShwC3
```

Please check our user guide for full tracker manual: https://github.com/geolink/opentracker/blob/master/docs/OpenTracker%202.4%20User%20Manual%201.4.pdf

**Comment by Chrescht** [comment]
Thanks, will try.
Other new issue: I get no response at all from the board, I was using another power source, 18V. No LEDs, nothing..how can I check if it is definitely dead?
Nowhere does it seem to have overheated, at least not visible to the naked eye.

**Comment by m4rkw** [comment]
@Chrescht 18V shouldn't have killed it, max on the spec is 32V. Is it recognised when connected via USB?

**Comment by ppescher** [comment]
Please check the Troubleshooting paragraph in the User Manual. You can try to force erase and see if you get a serial port (COM) when you connect the USB cable to your PC. Then you can reload some firmware on it.

**Comment by Chrescht** [comment]
Success, thanks guys! First I tried method 2, no success, but the first reset method seemed to have done the trick, I set remote key in tracker.h, uploaded the current firmware, set the APN by sms, then finally saw the correct GPS position in the LIVE map.
If I could I'd buy you a  🍺
