### ISSUE TITLE
geolink.io browser login: remember credentials

### ISSUE THREAD

**Issue by Chrescht** [geolink/opentracker#77]
At least Firefox is not proposing to save the login credentials for mydomain.geolink.io.
I take it this is a general issue.
Could you modify your login page such that the browsers recognize the login and thus ask to save the login?

**Comment by m4rkw** [comment]
Hi @Chrescht this is another issue that would probably be best handled via Geolink support.

**Comment by Chrescht** [comment]
@m4rkw you're right.
ps: it works now.
