### ISSUE TITLE
Can I connect to a HTTPS server?

### ISSUE THREAD

**Issue by LBreda** [geolink/opentracker#80]
Can I connect to a HTTPS server without getting only the "Moved permanently" error?

**Comment by ppescher** [comment]
Only HTTP has been implemented in stock OpenTracker firmware, but the modem does support HTTPS via dedicated AT commands.

**Comment by LBreda** [comment]
It's good enough for me. I checked the docs of the UG96 chip, and I didn't find anything useful. Could you give me some hint?

**Comment by ppescher** [comment]
What you need is the document "Quectel WCDMA UGxx TCPIP AT Commands Manual", which is available from the manufacturer after registration (See <https://www.quectel.com/support/downloads/ATCommandsManual.htm?keys=wcdma>).

**Comment by LBreda** [comment]
Thanks, I was reading a more general AT commands manual.

**Comment by ppescher** [comment]
Actually, there are other manuals for HTTPS but they are included in the list above:
"Quectel WCDMA UGxx SSL AT Commands Manual"
"Quectel WCDMA UGxx HTTP AT Commands Manual"

**Comment by LBreda** [comment]
Yep, found them. I'm having some trouble adapting the ack mechanism, tho.
